version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - ffmpeg
  jobs:
    pre_install:
      - python -m pip install opencv-python-headless ipywidgets

sphinx:
  configuration: docs/conf.py
  builder: "dirhtml"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
